# Generated by Django 5.2.6 on 2025-10-18 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_consultation_to_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('lab_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_type', models.CharField(max_length=100)),
                ('result_file', models.TextField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lab_results', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_results',
                'ordering': ['-upload_date'],
            },
        ),
    ]
