# Generated by Django 5.2.6 on 2025-10-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20251024_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='patient_photo',
            new_name='photo_url',
        ),
    ]
