# Generated by Django 5.2.6 on 2025-11-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20251024_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedService',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=150)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='booked_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booked_services',
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
    ]
