# Generated by Django 5.2.6 on 2025-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_appointment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveappointment',
            name='live_appointment_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
