# Generated by Django 5.2.6 on 2025-11-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_appointment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_made', to='myapp.doctor'),
        ),
    ]
