# Generated by Django 5.2.6 on 2025-11-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_add_prescription_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab_tech', 'Lab Technician'), ('patient', 'Patient')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['role'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('account', 'Account'), ('urgent', 'Urgent'), ('appointment', 'Appointment'), ('lab_result', 'Lab Result'), ('system', 'System'), ('password_reset', 'Password Reset Request')], max_length=50),
        ),
    ]
